### ISSUE TITLE
Support stdin

### ISSUE THREAD

**Issue by cxw42** [perlancar/perl-App-xsum#1]
Thank you for this tool!  Would you be willing to expand it to support data on stdin?  Currently

    echo foo | xsum -a crc32

fails since no filename is provided, and

    echo foo | xsum -a crc32 -

fails because File::Digest tests `-f` before calling `open` ([here](https://metacpan.org/source/PERLANCAR/File-Digest-0.007/lib/File/Digest.pm#L71)).  Thank you for considering this request!

**Comment by perlancar** [comment]
You're welcome. I wonder though how you found `xsum` and why you're using it :) It does not provide additional features to the Unix utilities `md5sum`, `sha1sum` et al and has quite a long list of Perl modules dependencies. 

Anyway, I've implemented what you requested. It's now in 0.002. Enjoy.

**Comment by cxw42** [comment]
Thanks for the quick turnaround!  I was looking on metacpan for crc32 and xsum popped up.  sum(1) at $work won't do crc32.  Much appreciated!

**Comment by perlancar** [comment]
Ah I see. Though it makes me curious what makes you still use CRC32 :)

**Comment by cxw42** [comment]
$work reasons ;) (I'm an embedded-system developer)
